import { CleaningDataType } from './cleaning-data-type.enum';

export enum CleaningReason {
  COMMON_AREA_DAILY = 'COMMON_AREA_DAILY',
  CHECKOUT_ROOM = 'CHECKOUT_ROOM',
  PRE_CHECKIN_ROOM = 'PRE_CHECKIN_ROOM',
  STAYOVER_ROOM = 'STAYOVER_ROOM',
}

export const CLEANING_REASON_VALUES = Object.values(CleaningReason);

export const CLEANING_REASON_LABEL: Record<CleaningReason, string> = {
  [CleaningReason.COMMON_AREA_DAILY]: 'Vệ sinh khu vực chung',
  [CleaningReason.CHECKOUT_ROOM]: 'Dọn phòng sau checkout',
  [CleaningReason.PRE_CHECKIN_ROOM]: 'Dọn phòng trước checkin',
  [CleaningReason.STAYOVER_ROOM]: 'Dọn phòng hằng ngày',
};

const CLEANING_REASON_MARKER = 'cleaningReason';

export function buildCleaningReasonComment(reason: CleaningReason, source: string): string {
  return `[${CLEANING_REASON_MARKER}:${reason}] Generated by ${source}`;
}

export function extractCleaningReasons(
  comment: string | null | undefined,
  fallbackDataType?: number,
): CleaningReason[] {
  const match = comment?.match(/\[cleaningReason:([A-Z_,]+)\]/);
  const reasons = match?.[1]
    ?.split(',')
    .filter((reason): reason is CleaningReason =>
      CLEANING_REASON_VALUES.includes(reason as CleaningReason),
    );

  if (reasons && reasons.length > 0) return reasons;

  if (fallbackDataType === Number(CleaningDataType.COMMON_AREA)) {
    return [CleaningReason.COMMON_AREA_DAILY];
  }
  if (fallbackDataType === Number(CleaningDataType.ROOM)) {
    return [CleaningReason.CHECKOUT_ROOM];
  }
  return [];
}
