/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffMasterRouteImport } from './routes/_authenticated/staff-master'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCleaningRouteImport } from './routes/_authenticated/cleaning'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'

const AuthenticatedStoreMasterLazyRouteImport = createFileRoute(
  '/_authenticated/store-master',
)()
const AuthenticatedRoomMasterLazyRouteImport = createFileRoute(
  '/_authenticated/room-master',
)()
const AuthenticatedRentsMasterLazyRouteImport = createFileRoute(
  '/_authenticated/rents-master',
)()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreMasterLazyRoute =
  AuthenticatedStoreMasterLazyRouteImport.update({
    id: '/store-master',
    path: '/store-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/store-master.lazy').then((d) => d.Route),
  )
const AuthenticatedRoomMasterLazyRoute =
  AuthenticatedRoomMasterLazyRouteImport.update({
    id: '/room-master',
    path: '/room-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/room-master.lazy').then((d) => d.Route),
  )
const AuthenticatedRentsMasterLazyRoute =
  AuthenticatedRentsMasterLazyRouteImport.update({
    id: '/rents-master',
    path: '/rents-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/rents-master.lazy').then((d) => d.Route),
  )
const AuthenticatedStaffMasterRoute =
  AuthenticatedStaffMasterRouteImport.update({
    id: '/staff-master',
    path: '/staff-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCleaningRoute = AuthenticatedCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/staff-master': typeof AuthenticatedStaffMasterRoute
  '/rents-master': typeof AuthenticatedRentsMasterLazyRoute
  '/room-master': typeof AuthenticatedRoomMasterLazyRoute
  '/store-master': typeof AuthenticatedStoreMasterLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/staff-master': typeof AuthenticatedStaffMasterRoute
  '/rents-master': typeof AuthenticatedRentsMasterLazyRoute
  '/room-master': typeof AuthenticatedRoomMasterLazyRoute
  '/store-master': typeof AuthenticatedStoreMasterLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/cleaning': typeof AuthenticatedCleaningRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/staff-master': typeof AuthenticatedStaffMasterRoute
  '/_authenticated/rents-master': typeof AuthenticatedRentsMasterLazyRoute
  '/_authenticated/room-master': typeof AuthenticatedRoomMasterLazyRoute
  '/_authenticated/store-master': typeof AuthenticatedStoreMasterLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/cleaning'
    | '/clients'
    | '/dashboard'
    | '/reservations'
    | '/rooms'
    | '/staff-master'
    | '/rents-master'
    | '/room-master'
    | '/store-master'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/billing'
    | '/cleaning'
    | '/clients'
    | '/dashboard'
    | '/reservations'
    | '/rooms'
    | '/staff-master'
    | '/rents-master'
    | '/room-master'
    | '/store-master'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/billing'
    | '/_authenticated/cleaning'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/reservations'
    | '/_authenticated/rooms'
    | '/_authenticated/staff-master'
    | '/_authenticated/rents-master'
    | '/_authenticated/room-master'
    | '/_authenticated/store-master'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store-master': {
      id: '/_authenticated/store-master'
      path: '/store-master'
      fullPath: '/store-master'
      preLoaderRoute: typeof AuthenticatedStoreMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/room-master': {
      id: '/_authenticated/room-master'
      path: '/room-master'
      fullPath: '/room-master'
      preLoaderRoute: typeof AuthenticatedRoomMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rents-master': {
      id: '/_authenticated/rents-master'
      path: '/rents-master'
      fullPath: '/rents-master'
      preLoaderRoute: typeof AuthenticatedRentsMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff-master': {
      id: '/_authenticated/staff-master'
      path: '/staff-master'
      fullPath: '/staff-master'
      preLoaderRoute: typeof AuthenticatedStaffMasterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cleaning': {
      id: '/_authenticated/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof AuthenticatedCleaningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCleaningRoute: typeof AuthenticatedCleaningRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedStaffMasterRoute: typeof AuthenticatedStaffMasterRoute
  AuthenticatedRentsMasterLazyRoute: typeof AuthenticatedRentsMasterLazyRoute
  AuthenticatedRoomMasterLazyRoute: typeof AuthenticatedRoomMasterLazyRoute
  AuthenticatedStoreMasterLazyRoute: typeof AuthenticatedStoreMasterLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCleaningRoute: AuthenticatedCleaningRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedStaffMasterRoute: AuthenticatedStaffMasterRoute,
  AuthenticatedRentsMasterLazyRoute: AuthenticatedRentsMasterLazyRoute,
  AuthenticatedRoomMasterLazyRoute: AuthenticatedRoomMasterLazyRoute,
  AuthenticatedStoreMasterLazyRoute: AuthenticatedStoreMasterLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
