/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffMasterRouteImport } from './routes/_authenticated/staff-master'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedReservationsCreateRouteImport } from './routes/_authenticated/reservations/create'

const AuthenticatedUsageSituationLazyRouteImport = createFileRoute(
  '/_authenticated/usage-situation',
)()
const AuthenticatedStoreMasterLazyRouteImport = createFileRoute(
  '/_authenticated/store-master',
)()
const AuthenticatedRoomMasterLazyRouteImport = createFileRoute(
  '/_authenticated/room-master',
)()
const AuthenticatedRoomAreaMasterLazyRouteImport = createFileRoute(
  '/_authenticated/room-area-master',
)()
const AuthenticatedRentsMasterLazyRouteImport = createFileRoute(
  '/_authenticated/rents-master',
)()
const AuthenticatedParkingSearchLazyRouteImport = createFileRoute(
  '/_authenticated/parking-search',
)()
const AuthenticatedParkingMasterLazyRouteImport = createFileRoute(
  '/_authenticated/parking-master',
)()
const AuthenticatedCleaningShiftLazyRouteImport = createFileRoute(
  '/_authenticated/cleaning-shift',
)()
const AuthenticatedCleaningLazyRouteImport = createFileRoute(
  '/_authenticated/cleaning',
)()
const AuthenticatedBicycleParkingMasterLazyRouteImport = createFileRoute(
  '/_authenticated/bicycle-parking-master',
)()
const AuthenticatedReservationsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/reservations/',
)()
const AuthenticatedClientsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/clients/',
)()
const AuthenticatedClientsCreateLazyRouteImport = createFileRoute(
  '/_authenticated/clients/create',
)()
const AuthenticatedReservationsReserveIdEditLazyRouteImport = createFileRoute(
  '/_authenticated/reservations/$reserveId/edit',
)()
const AuthenticatedReservationsReserveIdDetailLazyRouteImport = createFileRoute(
  '/_authenticated/reservations/$reserveId/detail',
)()
const AuthenticatedClientsClientIdEditLazyRouteImport = createFileRoute(
  '/_authenticated/clients/$clientId/edit',
)()
const AuthenticatedClientsClientIdDetailLazyRouteImport = createFileRoute(
  '/_authenticated/clients/$clientId/detail',
)()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsageSituationLazyRoute =
  AuthenticatedUsageSituationLazyRouteImport.update({
    id: '/usage-situation',
    path: '/usage-situation',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/usage-situation.lazy').then((d) => d.Route),
  )
const AuthenticatedStoreMasterLazyRoute =
  AuthenticatedStoreMasterLazyRouteImport.update({
    id: '/store-master',
    path: '/store-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/store-master.lazy').then((d) => d.Route),
  )
const AuthenticatedRoomMasterLazyRoute =
  AuthenticatedRoomMasterLazyRouteImport.update({
    id: '/room-master',
    path: '/room-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/room-master.lazy').then((d) => d.Route),
  )
const AuthenticatedRoomAreaMasterLazyRoute =
  AuthenticatedRoomAreaMasterLazyRouteImport.update({
    id: '/room-area-master',
    path: '/room-area-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/room-area-master.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedRentsMasterLazyRoute =
  AuthenticatedRentsMasterLazyRouteImport.update({
    id: '/rents-master',
    path: '/rents-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/rents-master.lazy').then((d) => d.Route),
  )
const AuthenticatedParkingSearchLazyRoute =
  AuthenticatedParkingSearchLazyRouteImport.update({
    id: '/parking-search',
    path: '/parking-search',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/parking-search.lazy').then((d) => d.Route),
  )
const AuthenticatedParkingMasterLazyRoute =
  AuthenticatedParkingMasterLazyRouteImport.update({
    id: '/parking-master',
    path: '/parking-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/parking-master.lazy').then((d) => d.Route),
  )
const AuthenticatedCleaningShiftLazyRoute =
  AuthenticatedCleaningShiftLazyRouteImport.update({
    id: '/cleaning-shift',
    path: '/cleaning-shift',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cleaning-shift.lazy').then((d) => d.Route),
  )
const AuthenticatedCleaningLazyRoute =
  AuthenticatedCleaningLazyRouteImport.update({
    id: '/cleaning',
    path: '/cleaning',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cleaning.lazy').then((d) => d.Route),
  )
const AuthenticatedBicycleParkingMasterLazyRoute =
  AuthenticatedBicycleParkingMasterLazyRouteImport.update({
    id: '/bicycle-parking-master',
    path: '/bicycle-parking-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bicycle-parking-master.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStaffMasterRoute =
  AuthenticatedStaffMasterRouteImport.update({
    id: '/staff-master',
    path: '/staff-master',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReservationsIndexLazyRoute =
  AuthenticatedReservationsIndexLazyRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/reservations/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedClientsIndexLazyRoute =
  AuthenticatedClientsIndexLazyRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clients/index.lazy').then((d) => d.Route),
  )
const AuthenticatedClientsCreateLazyRoute =
  AuthenticatedClientsCreateLazyRouteImport.update({
    id: '/clients/create',
    path: '/clients/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clients/create.lazy').then((d) => d.Route),
  )
const AuthenticatedReservationsCreateRoute =
  AuthenticatedReservationsCreateRouteImport.update({
    id: '/reservations/create',
    path: '/reservations/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/reservations/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedReservationsReserveIdEditLazyRoute =
  AuthenticatedReservationsReserveIdEditLazyRouteImport.update({
    id: '/reservations/$reserveId/edit',
    path: '/reservations/$reserveId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/reservations/$reserveId/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedReservationsReserveIdDetailLazyRoute =
  AuthenticatedReservationsReserveIdDetailLazyRouteImport.update({
    id: '/reservations/$reserveId/detail',
    path: '/reservations/$reserveId/detail',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/reservations/$reserveId/detail.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedClientsClientIdEditLazyRoute =
  AuthenticatedClientsClientIdEditLazyRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clients/$clientId/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedClientsClientIdDetailLazyRoute =
  AuthenticatedClientsClientIdDetailLazyRouteImport.update({
    id: '/clients/$clientId/detail',
    path: '/clients/$clientId/detail',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clients/$clientId/detail.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/staff-master': typeof AuthenticatedStaffMasterRoute
  '/bicycle-parking-master': typeof AuthenticatedBicycleParkingMasterLazyRoute
  '/cleaning': typeof AuthenticatedCleaningLazyRoute
  '/cleaning-shift': typeof AuthenticatedCleaningShiftLazyRoute
  '/parking-master': typeof AuthenticatedParkingMasterLazyRoute
  '/parking-search': typeof AuthenticatedParkingSearchLazyRoute
  '/rents-master': typeof AuthenticatedRentsMasterLazyRoute
  '/room-area-master': typeof AuthenticatedRoomAreaMasterLazyRoute
  '/room-master': typeof AuthenticatedRoomMasterLazyRoute
  '/store-master': typeof AuthenticatedStoreMasterLazyRoute
  '/usage-situation': typeof AuthenticatedUsageSituationLazyRoute
  '/reservations/create': typeof AuthenticatedReservationsCreateRoute
  '/clients/create': typeof AuthenticatedClientsCreateLazyRoute
  '/clients/': typeof AuthenticatedClientsIndexLazyRoute
  '/reservations/': typeof AuthenticatedReservationsIndexLazyRoute
  '/clients/$clientId/detail': typeof AuthenticatedClientsClientIdDetailLazyRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditLazyRoute
  '/reservations/$reserveId/detail': typeof AuthenticatedReservationsReserveIdDetailLazyRoute
  '/reservations/$reserveId/edit': typeof AuthenticatedReservationsReserveIdEditLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/staff-master': typeof AuthenticatedStaffMasterRoute
  '/bicycle-parking-master': typeof AuthenticatedBicycleParkingMasterLazyRoute
  '/cleaning': typeof AuthenticatedCleaningLazyRoute
  '/cleaning-shift': typeof AuthenticatedCleaningShiftLazyRoute
  '/parking-master': typeof AuthenticatedParkingMasterLazyRoute
  '/parking-search': typeof AuthenticatedParkingSearchLazyRoute
  '/rents-master': typeof AuthenticatedRentsMasterLazyRoute
  '/room-area-master': typeof AuthenticatedRoomAreaMasterLazyRoute
  '/room-master': typeof AuthenticatedRoomMasterLazyRoute
  '/store-master': typeof AuthenticatedStoreMasterLazyRoute
  '/usage-situation': typeof AuthenticatedUsageSituationLazyRoute
  '/reservations/create': typeof AuthenticatedReservationsCreateRoute
  '/clients/create': typeof AuthenticatedClientsCreateLazyRoute
  '/clients': typeof AuthenticatedClientsIndexLazyRoute
  '/reservations': typeof AuthenticatedReservationsIndexLazyRoute
  '/clients/$clientId/detail': typeof AuthenticatedClientsClientIdDetailLazyRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditLazyRoute
  '/reservations/$reserveId/detail': typeof AuthenticatedReservationsReserveIdDetailLazyRoute
  '/reservations/$reserveId/edit': typeof AuthenticatedReservationsReserveIdEditLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/staff-master': typeof AuthenticatedStaffMasterRoute
  '/_authenticated/bicycle-parking-master': typeof AuthenticatedBicycleParkingMasterLazyRoute
  '/_authenticated/cleaning': typeof AuthenticatedCleaningLazyRoute
  '/_authenticated/cleaning-shift': typeof AuthenticatedCleaningShiftLazyRoute
  '/_authenticated/parking-master': typeof AuthenticatedParkingMasterLazyRoute
  '/_authenticated/parking-search': typeof AuthenticatedParkingSearchLazyRoute
  '/_authenticated/rents-master': typeof AuthenticatedRentsMasterLazyRoute
  '/_authenticated/room-area-master': typeof AuthenticatedRoomAreaMasterLazyRoute
  '/_authenticated/room-master': typeof AuthenticatedRoomMasterLazyRoute
  '/_authenticated/store-master': typeof AuthenticatedStoreMasterLazyRoute
  '/_authenticated/usage-situation': typeof AuthenticatedUsageSituationLazyRoute
  '/_authenticated/reservations/create': typeof AuthenticatedReservationsCreateRoute
  '/_authenticated/clients/create': typeof AuthenticatedClientsCreateLazyRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexLazyRoute
  '/_authenticated/reservations/': typeof AuthenticatedReservationsIndexLazyRoute
  '/_authenticated/clients/$clientId/detail': typeof AuthenticatedClientsClientIdDetailLazyRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditLazyRoute
  '/_authenticated/reservations/$reserveId/detail': typeof AuthenticatedReservationsReserveIdDetailLazyRoute
  '/_authenticated/reservations/$reserveId/edit': typeof AuthenticatedReservationsReserveIdEditLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/rooms'
    | '/staff-master'
    | '/bicycle-parking-master'
    | '/cleaning'
    | '/cleaning-shift'
    | '/parking-master'
    | '/parking-search'
    | '/rents-master'
    | '/room-area-master'
    | '/room-master'
    | '/store-master'
    | '/usage-situation'
    | '/reservations/create'
    | '/clients/create'
    | '/clients/'
    | '/reservations/'
    | '/clients/$clientId/detail'
    | '/clients/$clientId/edit'
    | '/reservations/$reserveId/detail'
    | '/reservations/$reserveId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/rooms'
    | '/staff-master'
    | '/bicycle-parking-master'
    | '/cleaning'
    | '/cleaning-shift'
    | '/parking-master'
    | '/parking-search'
    | '/rents-master'
    | '/room-area-master'
    | '/room-master'
    | '/store-master'
    | '/usage-situation'
    | '/reservations/create'
    | '/clients/create'
    | '/clients'
    | '/reservations'
    | '/clients/$clientId/detail'
    | '/clients/$clientId/edit'
    | '/reservations/$reserveId/detail'
    | '/reservations/$reserveId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/rooms'
    | '/_authenticated/staff-master'
    | '/_authenticated/bicycle-parking-master'
    | '/_authenticated/cleaning'
    | '/_authenticated/cleaning-shift'
    | '/_authenticated/parking-master'
    | '/_authenticated/parking-search'
    | '/_authenticated/rents-master'
    | '/_authenticated/room-area-master'
    | '/_authenticated/room-master'
    | '/_authenticated/store-master'
    | '/_authenticated/usage-situation'
    | '/_authenticated/reservations/create'
    | '/_authenticated/clients/create'
    | '/_authenticated/clients/'
    | '/_authenticated/reservations/'
    | '/_authenticated/clients/$clientId/detail'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/reservations/$reserveId/detail'
    | '/_authenticated/reservations/$reserveId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usage-situation': {
      id: '/_authenticated/usage-situation'
      path: '/usage-situation'
      fullPath: '/usage-situation'
      preLoaderRoute: typeof AuthenticatedUsageSituationLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/store-master': {
      id: '/_authenticated/store-master'
      path: '/store-master'
      fullPath: '/store-master'
      preLoaderRoute: typeof AuthenticatedStoreMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/room-master': {
      id: '/_authenticated/room-master'
      path: '/room-master'
      fullPath: '/room-master'
      preLoaderRoute: typeof AuthenticatedRoomMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/room-area-master': {
      id: '/_authenticated/room-area-master'
      path: '/room-area-master'
      fullPath: '/room-area-master'
      preLoaderRoute: typeof AuthenticatedRoomAreaMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rents-master': {
      id: '/_authenticated/rents-master'
      path: '/rents-master'
      fullPath: '/rents-master'
      preLoaderRoute: typeof AuthenticatedRentsMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parking-search': {
      id: '/_authenticated/parking-search'
      path: '/parking-search'
      fullPath: '/parking-search'
      preLoaderRoute: typeof AuthenticatedParkingSearchLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parking-master': {
      id: '/_authenticated/parking-master'
      path: '/parking-master'
      fullPath: '/parking-master'
      preLoaderRoute: typeof AuthenticatedParkingMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cleaning-shift': {
      id: '/_authenticated/cleaning-shift'
      path: '/cleaning-shift'
      fullPath: '/cleaning-shift'
      preLoaderRoute: typeof AuthenticatedCleaningShiftLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cleaning': {
      id: '/_authenticated/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof AuthenticatedCleaningLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bicycle-parking-master': {
      id: '/_authenticated/bicycle-parking-master'
      path: '/bicycle-parking-master'
      fullPath: '/bicycle-parking-master'
      preLoaderRoute: typeof AuthenticatedBicycleParkingMasterLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff-master': {
      id: '/_authenticated/staff-master'
      path: '/staff-master'
      fullPath: '/staff-master'
      preLoaderRoute: typeof AuthenticatedStaffMasterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations/': {
      id: '/_authenticated/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof AuthenticatedReservationsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/create': {
      id: '/_authenticated/clients/create'
      path: '/clients/create'
      fullPath: '/clients/create'
      preLoaderRoute: typeof AuthenticatedClientsCreateLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations/create': {
      id: '/_authenticated/reservations/create'
      path: '/reservations/create'
      fullPath: '/reservations/create'
      preLoaderRoute: typeof AuthenticatedReservationsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations/$reserveId/edit': {
      id: '/_authenticated/reservations/$reserveId/edit'
      path: '/reservations/$reserveId/edit'
      fullPath: '/reservations/$reserveId/edit'
      preLoaderRoute: typeof AuthenticatedReservationsReserveIdEditLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations/$reserveId/detail': {
      id: '/_authenticated/reservations/$reserveId/detail'
      path: '/reservations/$reserveId/detail'
      fullPath: '/reservations/$reserveId/detail'
      preLoaderRoute: typeof AuthenticatedReservationsReserveIdDetailLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId/detail': {
      id: '/_authenticated/clients/$clientId/detail'
      path: '/clients/$clientId/detail'
      fullPath: '/clients/$clientId/detail'
      preLoaderRoute: typeof AuthenticatedClientsClientIdDetailLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedStaffMasterRoute: typeof AuthenticatedStaffMasterRoute
  AuthenticatedBicycleParkingMasterLazyRoute: typeof AuthenticatedBicycleParkingMasterLazyRoute
  AuthenticatedCleaningLazyRoute: typeof AuthenticatedCleaningLazyRoute
  AuthenticatedCleaningShiftLazyRoute: typeof AuthenticatedCleaningShiftLazyRoute
  AuthenticatedParkingMasterLazyRoute: typeof AuthenticatedParkingMasterLazyRoute
  AuthenticatedParkingSearchLazyRoute: typeof AuthenticatedParkingSearchLazyRoute
  AuthenticatedRentsMasterLazyRoute: typeof AuthenticatedRentsMasterLazyRoute
  AuthenticatedRoomAreaMasterLazyRoute: typeof AuthenticatedRoomAreaMasterLazyRoute
  AuthenticatedRoomMasterLazyRoute: typeof AuthenticatedRoomMasterLazyRoute
  AuthenticatedStoreMasterLazyRoute: typeof AuthenticatedStoreMasterLazyRoute
  AuthenticatedUsageSituationLazyRoute: typeof AuthenticatedUsageSituationLazyRoute
  AuthenticatedReservationsCreateRoute: typeof AuthenticatedReservationsCreateRoute
  AuthenticatedClientsCreateLazyRoute: typeof AuthenticatedClientsCreateLazyRoute
  AuthenticatedClientsIndexLazyRoute: typeof AuthenticatedClientsIndexLazyRoute
  AuthenticatedReservationsIndexLazyRoute: typeof AuthenticatedReservationsIndexLazyRoute
  AuthenticatedClientsClientIdDetailLazyRoute: typeof AuthenticatedClientsClientIdDetailLazyRoute
  AuthenticatedClientsClientIdEditLazyRoute: typeof AuthenticatedClientsClientIdEditLazyRoute
  AuthenticatedReservationsReserveIdDetailLazyRoute: typeof AuthenticatedReservationsReserveIdDetailLazyRoute
  AuthenticatedReservationsReserveIdEditLazyRoute: typeof AuthenticatedReservationsReserveIdEditLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedStaffMasterRoute: AuthenticatedStaffMasterRoute,
  AuthenticatedBicycleParkingMasterLazyRoute:
    AuthenticatedBicycleParkingMasterLazyRoute,
  AuthenticatedCleaningLazyRoute: AuthenticatedCleaningLazyRoute,
  AuthenticatedCleaningShiftLazyRoute: AuthenticatedCleaningShiftLazyRoute,
  AuthenticatedParkingMasterLazyRoute: AuthenticatedParkingMasterLazyRoute,
  AuthenticatedParkingSearchLazyRoute: AuthenticatedParkingSearchLazyRoute,
  AuthenticatedRentsMasterLazyRoute: AuthenticatedRentsMasterLazyRoute,
  AuthenticatedRoomAreaMasterLazyRoute: AuthenticatedRoomAreaMasterLazyRoute,
  AuthenticatedRoomMasterLazyRoute: AuthenticatedRoomMasterLazyRoute,
  AuthenticatedStoreMasterLazyRoute: AuthenticatedStoreMasterLazyRoute,
  AuthenticatedUsageSituationLazyRoute: AuthenticatedUsageSituationLazyRoute,
  AuthenticatedReservationsCreateRoute: AuthenticatedReservationsCreateRoute,
  AuthenticatedClientsCreateLazyRoute: AuthenticatedClientsCreateLazyRoute,
  AuthenticatedClientsIndexLazyRoute: AuthenticatedClientsIndexLazyRoute,
  AuthenticatedReservationsIndexLazyRoute:
    AuthenticatedReservationsIndexLazyRoute,
  AuthenticatedClientsClientIdDetailLazyRoute:
    AuthenticatedClientsClientIdDetailLazyRoute,
  AuthenticatedClientsClientIdEditLazyRoute:
    AuthenticatedClientsClientIdEditLazyRoute,
  AuthenticatedReservationsReserveIdDetailLazyRoute:
    AuthenticatedReservationsReserveIdDetailLazyRoute,
  AuthenticatedReservationsReserveIdEditLazyRoute:
    AuthenticatedReservationsReserveIdEditLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
